class Team {
 String namaTeam;
 String logo;
 String deskripsi;
 List<String> namaPemain;
 List<String> fotoPemain;

 Team(
 { required this.namaTeam,
   required this.logo,
   required this.deskripsi,
   required this.namaPemain,
   required this.fotoPemain});
}

var teamList =[
  Team(namaTeam: "Alter Ego",
      logo: "https://id-mpl.com/uploads/SEASON-6/data/ae/team/alter-ego-512.png",
      deskripsi: "Alter Ego adalah tim yang dijuluki kuda hitam tetapi perlahan-lahan mampu menunjukkan kemampuannya dari waktu ke waktu. Mulai dari MPL S2, Alter Ego tidak lolos. Di MPL S3 Alter Ego meningkatkan peringkatnya ke posisi ke-5, dan akhirnya di MPL S4 Alter Ego berhasil mencapai posisi ke-3, tetapi perjalanannya tidak hanya berakhir di sana. Alter Ego akan terus tumbuh.",
      namaPemain: ["Ahmad","Leomurphy","Caesius","Celiboy","Yam","Pai","Udil"],
      fotoPemain: ["https://id-mpl.com/uploads/SEASON-7/players/AE/Ahmad_2.png",
                    "https://id-mpl.com/uploads/SEASON-7/players/AE/Leomurphy_2.png",
                    "https://id-mpl.com/uploads/SEASON-7/players/AE/Caesius_2.png",
                    "https://id-mpl.com/uploads/SEASON-7/players/AE/Celiboy_2.png",
                    "https://id-mpl.com/uploads/SEASON-7/players/AE/Yam_2.png",
                    "https://id-mpl.com/uploads/SEASON-7/players/AE/Pai_2.png",
                    "https://id-mpl.com/uploads/SEASON-7/players/AE/Udil_2.png"]),

  Team(namaTeam: "Bigetron Alpha",
      logo: "https://id-mpl.com/uploads/SEASON-6/data/btr/team/bigetron-512.png",
      deskripsi: "Perjalan Team Mobile legend Bigetron eSports di mulai pada MpL season 1, Awal mula munculnya team Bigetron sempat mengguncang dunia Mobile Legend dimana bigetron melahirkan bintang- bintang mobile legends yang sekarang menjadi bintang seperti Eiduart,Emperor,Rekt, dan Fabiens Bigetron eSports juga tidak pernah melewatkan season MPL, kita selalu berpartisipasi di setiap season nya sampai sekarang. Pada MPL season 3, Bigetron eSports melakukan perombakan besar-besaran, Berawal dari transisi player dari game PC ke mobile legend, setelah melakukan tryout yang cukup panjang menyisakan 2 player Bravo dan DreamS, Bravo dan Dreams yang mampu overcome dan beradaptasi memulai perjalanan baru bersama bigetron di qualifier MPL Season 3 bersama Vyn,Branz,Lynx,Xora, Taka,zoeybit .dan berhasil lolos ke babak playoff dan muncul sebagai kuda hitam dengan mengalahkan sang raja bertahan RRQ di babak playoff.",
      namaPemain: ["Renbo","KYY","Dreams","Branz","RIPPO","MATT","MAXXX"],
      fotoPemain: ["https://id-mpl.com/uploads/SEASON-7/players/BTR/RENBO-2.png",
        "https://id-mpl.com/uploads/SEASON-7/players/BTR/KYY-2.png",
        "https://id-mpl.com/uploads/SEASON-7/players/BTR/DREAMS-2.png",
        "https://id-mpl.com/uploads/SEASON-7/players/BTR/BRANZ-2.png",
        "https://id-mpl.com/uploads/SEASON-7/players/BTR/RIPPO-2.png",
        "https://id-mpl.com/uploads/SEASON-7/players/BTR/MATT-2.png",
        "https://id-mpl.com/uploads/SEASON-7/players/BTR/MAXXX-2.png"]),
  Team(namaTeam: "EVOS Legend",
      logo: "https://id-mpl.com/uploads/SEASON-6/data/evos/team/evos-512.png",
      deskripsi: "EVOS Esports dibentuk pada 1 September 2016 dimulai dengan divisi Dota. Setelah mencapai keberhasilan kecil dalam Judul PC, tim mulai bercabang ke dalam game lain dan Mobile Legends lahir. Tim mengambil Team Lord pada awalnya dan sukses baik di kompetisi kecil. Setelah lelah kalah di turnamen besar, tim melakukan pertukaran roster besar, mengambil bintang muda, JessNoLimit & Oura. Dari sana tim mulai mendapatkan traksi, terutama menyelesaikan tempat ke-2 di MPL pertama.",
      namaPemain: ["R E K T","WANNN","Luminaire","Antimage","LJ","Clover","Ferxiic"],
      fotoPemain: ["https://id-mpl.com/uploads/SEASON-7/players/EVOS/REKT-2.png",
        "https://id-mpl.com/uploads/SEASON-7/players/EVOS/WANN-2.png",
        "https://id-mpl.com/uploads/SEASON-7/players/EVOS/LUMINAIRE-2.png",
        "https://id-mpl.com/uploads/SEASON-7/players/EVOS/ANTIMAGE-2.png",
        "https://id-mpl.com/uploads/SEASON-7/players/EVOS/LJ-2.png",
        "https://id-mpl.com/uploads/SEASON-7/players/EVOS/CLOVER-2.png",
        "https://id-mpl.com/uploads/SEASON-7/players/EVOS/FERXIIC-2.png"]),
  Team(namaTeam: "Genflix Aerowolf",
      logo: "https://id-mpl.com/uploads/SEASON-6/data/gflx/team/aerowolf-genflix-512.png",
      deskripsi: "Genflix Aerowolf diresmikan pada tanggal 20 Mei 2019. Untuk line-up pemain Genflix Aerowolf sendiri diumumkan pada tanggal 23 July 2019 di mana line-up ini dititik fokuskan untuk MPL Indonesia Season 4. Genflix Aerowolf adalah tim Mobile Legends dari Aerowolf Pro Team yang memiliki kemitraan eksklusif dengan layanan video online gratis dan berbayar (baik streaming maupun unduhan) yang dikenal sebagai Genflix. Aerowolf Pro Team sendiri adalah tim Esports berbasis di Jakarta, Indonesia, yang sudah mengikuti lebih dari 25 kejuaraan nasional dan internasional",
      namaPemain: ["Bravo","Fredoqt","Bottle","Rinazmi","Clay","M A R Z","Watt"],
      fotoPemain: ["https://id-mpl.com/uploads/SEASON-7/players/GFLX/BRAVO-2.png",
        "https://id-mpl.com/uploads/SEASON-7/players/GFLX/FREDO-2.png",
        "https://id-mpl.com/uploads/SEASON-7/players/GFLX/BOTTLE-2.png",
        "https://id-mpl.com/uploads/SEASON-7/players/GFLX/RINAZM-2I.png",
        "https://id-mpl.com/uploads/SEASON-7/players/GFLX/CLAY-2.png",
        "https://id-mpl.com/uploads/SEASON-7/players/GFLX/MARZ-2.png",
        "https://id-mpl.com/uploads/SEASON-7/players/GFLX/WATT-2.png"]),
  Team(namaTeam: "Onic Esport",
      logo: "https://id-mpl.com/uploads/SEASON-6/data/onic/team/onic-black-256.png",
      deskripsi: "Kami adalah Tim Manajemen E-Sports Profesional. Didirikan pada tahun 2018, kami bertujuan untuk menjadi organisasi e-sports terbaik untuk mewakili Asia Tenggara. Kami mengelola bakat dan membuat mereka bersinar. ONIC dibangun dengan keyakinan di mana kita melihat masa depan hiburan adalah e-sports. Dunia e-sports di Indonesia baru pada tahap awal, dan ONIC ada di sini untuk meningkatkan permainan.",
      namaPemain: ["Sasa","Drian","Kiboy","S A N Z","Rasy","CW","Butsss"],
      fotoPemain: ["https://id-mpl.com/uploads/SEASON-7/players/ONIC/sasa-2.png",
        "https://id-mpl.com/uploads/SEASON-7/players/ONIC/drian-2.png",
        "https://id-mpl.com/uploads/SEASON-7/players/ONIC/kiboy-2.png",
        "https://id-mpl.com/uploads/SEASON-7/players/ONIC/sanz-2.png",
        "https://id-mpl.com/uploads/SEASON-7/players/ONIC/rasy-2.png",
        "https://id-mpl.com/uploads/SEASON-7/players/ONIC/cw-2.png",
        "https://id-mpl.com/uploads/SEASON-7/players/ONIC/butsss-2.png"]),
  Team(namaTeam: "RRQ Hoshi",
      logo: "https://id-mpl.com/uploads/SEASON-6/data/rrq/team/rrq-512.png",
      deskripsi: "Kami adalah Tim Manajemen E-Sports Profesional. Didirikan pada tahun 2018, kami bertujuan untuk menjadi organisasi e-sports terbaik untuk mewakili Asia Tenggara. Kami mengelola bakat dan membuat mereka bersinar. ONIC dibangun dengan keyakinan di mana kita melihat masa depan hiburan adalah e-sports. Dunia e-sports di Indonesia baru pada tahap awal, dan ONIC ada di sini untuk meningkatkan permainan.",
      namaPemain: ["Vynnn","R7","Lemon","Skylar","Alberttt","Psychoo","Taka"],
      fotoPemain: ["https://id-mpl.com/uploads/SEASON-7/players/RRQ/VYNNN-2.png",
        "https://id-mpl.com/uploads/SEASON-7/players/RRQ/R7-2.png",
        "https://id-mpl.com/uploads/SEASON-7/players/RRQ/LEMON-2.png",
        "https://id-mpl.com/uploads/SEASON-7/players/RRQ/SKYLAR-2.png",
        "https://id-mpl.com/uploads/SEASON-7/players/RRQ/ALBERTTT-2.png",
        "https://id-mpl.com/uploads/SEASON-7/players/RRQ/PSYCHO-2.png",
        "https://id-mpl.com/uploads/SEASON-7/players/RRQ/TAKA-2.png",]),
];